AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sample-stepfunction-python3.7

Parameters:
  EnvPrefix:
    Type: String
    Default: sampleApp

Globals:
  Function:
    Timeout: 1000
    Environment:
      Variables:
        TZ: Asia/Tokyo
        EnvPrefix: !Ref EnvPrefix
        LOG_LEVEL: INFO
              
Resources:
  AwsLambdaPowertoolsPythonLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:057560766410:applications/aws-lambda-powertools-python-layer
        SemanticVersion: 1.11.0

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Layers:
        - !GetAtt AwsLambdaPowertoolsPythonLayer.Outputs.LayerVersionArn
      FunctionName: !Sub ${EnvPrefix}YokotenCheck
      CodeUri: functions/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get

Outputs:
  
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
